vim.g.colors_name = "wallust"

local ok, c = pcall(dofile, vim.fn.stdpath("config") .. "/lua/wallust-colors.lua")
if not ok then
  vim.cmd.colorscheme("oxocarbon")
  return
end

local bg = c.background
local fg = c.foreground
local c0, c1, c2 = c.color0, c.color1, c.color2
local c3, c4, c5, c6 = c.color3, c.color4, c.color5, c.color6
local c7, c8, c9, c10 = c.color7, c.color8, c.color9, c.color10
local c11, c12, c13 = c.color11, c.color12, c.color13
local c14, c15 = c.color14, c.color15

local hl = vim.api.nvim_set_hl

hl(0, "Normal", { fg = fg, bg = bg })
hl(0, "NormalFloat", { fg = fg, bg = c0 })
hl(0, "NormalNC", { fg = fg, bg = bg })
hl(0, "EndOfBuffer", { fg = c0 })
hl(0, "NonText", { fg = c8 })
hl(0, "Whitespace", { fg = c8 })
hl(0, "Conceal", { fg = c8 })
hl(0, "Cursor", { fg = bg, bg = c.cursor })
hl(0, "CursorIM", { fg = bg, bg = c.cursor })
hl(0, "CursorColumn", { bg = c0 })
hl(0, "CursorLine", { bg = c0 })
hl(0, "CursorLineNr", { fg = c5, bold = true })
hl(0, "LineNr", { fg = c8 })
hl(0, "SignColumn", { bg = bg })
hl(0, "ColorColumn", { bg = c0 })
hl(0, "FoldColumn", { fg = c8, bg = bg })
hl(0, "Folded", { fg = c8, bg = c0 })
hl(0, "VertSplit", { fg = c8, bg = bg })
hl(0, "WinSeparator", { fg = c8, bg = bg })
hl(0, "MatchParen", { fg = c5, bold = true })
hl(0, "Visual", { bg = c2 })
hl(0, "VisualNOS", { bg = c2 })
hl(0, "Search", { fg = bg, bg = c5 })
hl(0, "CurSearch", { fg = bg, bg = c1 })
hl(0, "IncSearch", { fg = bg, bg = c3 })
hl(0, "Substitute", { fg = bg, bg = c5 })
hl(0, "QuickFixLine", { bg = c2 })
hl(0, "Pmenu", { fg = fg, bg = c0 })
hl(0, "PmenuSel", { fg = bg, bg = c5 })
hl(0, "PmenuSbar", { bg = c0 })
hl(0, "PmenuThumb", { bg = c8 })
hl(0, "WildMenu", { fg = c5, bg = c0 })
hl(0, "Question", { fg = c3 })
hl(0, "MoreMsg", { fg = c3 })
hl(0, "WarningMsg", { fg = c1 })
hl(0, "ErrorMsg", { fg = bg, bg = c1 })
hl(0, "ModeMsg", { fg = fg })
hl(0, "Directory", { fg = c5 })
hl(0, "Title", { fg = c5, bold = true })
hl(0, "TabLine", { fg = c8, bg = c0 })
hl(0, "TabLineFill", { bg = c0 })
hl(0, "TabLineSel", { fg = fg, bg = bg })
hl(0, "StatusLine", { fg = fg, bg = c0 })
hl(0, "StatusLineNC", { fg = c8, bg = c0 })
hl(0, "WildMenu", { fg = fg, bg = c1 })
hl(0, "SpellBad", { sp = c1, undercurl = true })
hl(0, "SpellCap", { sp = c3, undercurl = true })
hl(0, "SpellLocal", { sp = c3, undercurl = true })
hl(0, "SpellRare", { sp = c5, undercurl = true })
hl(0, "DiffAdd", { bg = c2 })
hl(0, "DiffChange", { bg = c3 })
hl(0, "DiffDelete", { bg = c1 })
hl(0, "DiffText", { bg = c5 })
hl(0, "diffAdded", { fg = c3 })
hl(0, "diffRemoved", { fg = c1 })
hl(0, "diffChanged", { fg = c5 })

hl(0, "Comment", { fg = c8, italic = true })
hl(0, "Constant", { fg = c9 })
hl(0, "String", { fg = c4 })
hl(0, "Character", { fg = c4 })
hl(0, "Number", { fg = c9 })
hl(0, "Boolean", { fg = c9 })
hl(0, "Float", { fg = c9 })
hl(0, "Identifier", { fg = c6 })
hl(0, "Function", { fg = c5 })
hl(0, "Statement", { fg = c5 })
hl(0, "Conditional", { fg = c5 })
hl(0, "Repeat", { fg = c5 })
hl(0, "Label", { fg = c5 })
hl(0, "Operator", { fg = c3 })
hl(0, "Keyword", { fg = c5 })
hl(0, "Exception", { fg = c1 })
hl(0, "PreProc", { fg = c9 })
hl(0, "Include", { fg = c5 })
hl(0, "Define", { fg = c5 })
hl(0, "Macro", { fg = c5 })
hl(0, "PreCondit", { fg = c5 })
hl(0, "Type", { fg = c3 })
hl(0, "StorageClass", { fg = c3 })
hl(0, "Structure", { fg = c3 })
hl(0, "Typedef", { fg = c3 })
hl(0, "Special", { fg = c11 })
hl(0, "SpecialChar", { fg = c11 })
hl(0, "Tag", { fg = c5 })
hl(0, "Delimiter", { fg = c8 })
hl(0, "SpecialComment", { fg = c8 })
hl(0, "Debug", { fg = c1 })
hl(0, "Underlined", { underline = true })
hl(0, "Ignore", { fg = c8 })
hl(0, "Todo", { fg = bg, bg = c3 })
hl(0, "Error", { fg = bg, bg = c1 })

hl(0, "@comment", { link = "Comment" })
hl(0, "@error", { link = "Error" })
hl(0, "@none", {})
hl(0, "@preproc", { link = "PreProc" })
hl(0, "@define", { link = "Define" })
hl(0, "@operator", { link = "Operator" })

hl(0, "@punctuation.delimiter", { link = "Delimiter" })
hl(0, "@punctuation.bracket", { fg = fg })
hl(0, "@punctuation.special", { link = "Special" })

hl(0, "@string", { link = "String" })
hl(0, "@string.regex", { link = "String" })
hl(0, "@string.escape", { fg = c11 })
hl(0, "@string.special", { link = "SpecialChar" })

hl(0, "@character", { link = "Character" })
hl(0, "@character.special", { link = "SpecialChar" })

hl(0, "@boolean", { link = "Boolean" })
hl(0, "@number", { link = "Number" })
hl(0, "@float", { link = "Float" })

hl(0, "@function", { link = "Function" })
hl(0, "@function.builtin", { fg = c1 })
hl(0, "@function.call", { link = "Function" })
hl(0, "@function.macro", { link = "Macro" })
hl(0, "@function.method", { link = "Function" })
hl(0, "@function.method.call", { link = "Function" })
hl(0, "@constructor", { fg = c9 })
hl(0, "@parameter", { fg = c6 })
hl(0, "@method", { link = "Function" })
hl(0, "@field", { fg = c6 })
hl(0, "@property", { fg = c6 })

hl(0, "@variable", { fg = fg })
hl(0, "@variable.builtin", { fg = c1 })
hl(0, "@variable.member", { fg = c6 })
hl(0, "@variable.parameter", { fg = c6 })

hl(0, "@constant", { link = "Constant" })
hl(0, "@constant.builtin", { fg = c1 })
hl(0, "@constant.macro", { link = "Define" })

hl(0, "@type", { link = "Type" })
hl(0, "@type.builtin", { fg = c3 })
hl(0, "@type.definition", { link = "Typedef" })
hl(0, "@type.qualifier", { link = "Type" })

hl(0, "@keyword", { link = "Keyword" })
hl(0, "@keyword.function", { link = "Keyword" })
hl(0, "@keyword.operator", { fg = c3 })
hl(0, "@keyword.import", { link = "Include" })
hl(0, "@keyword.storage", { link = "StorageClass" })
hl(0, "@keyword.repeat", { link = "Repeat" })
hl(0, "@keyword.return", { link = "Keyword" })
hl(0, "@keyword.debug", { link = "Debug" })
hl(0, "@keyword.exception", { link = "Exception" })
hl(0, "@keyword.conditional", { link = "Conditional" })
hl(0, "@keyword.directive", { link = "PreProc" })
hl(0, "@keyword.directive.define", { link = "Define" })

hl(0, "@label", { link = "Label" })

hl(0, "@include", { link = "Include" })

hl(0, "@tag", { link = "Tag" })
hl(0, "@tag.attribute", { fg = c6 })
hl(0, "@tag.delimiter", { fg = c8 })

hl(0, "@text", { link = "Normal" })
hl(0, "@text.strong", { bold = true })
hl(0, "@text.emphasis", { italic = true })
hl(0, "@text.underline", { underline = true })
hl(0, "@text.strike", { strikethrough = true })
hl(0, "@text.title", { link = "Title" })
hl(0, "@text.literal", { fg = c4 })
hl(0, "@text.uri", { link = "Underlined" })
hl(0, "@text.math", { fg = c11 })
hl(0, "@text.environment", { fg = c5 })
hl(0, "@text.environment.name", { fg = c3 })
hl(0, "@text.note", { fg = bg, bg = c3 })
hl(0, "@text.warning", { fg = bg, bg = c1 })
hl(0, "@text.danger", { fg = bg, bg = c1 })
hl(0, "@text.diff.add", { link = "diffAdded" })
hl(0, "@text.diff.delete", { link = "diffRemoved" })

hl(0, "@diff.plus", { link = "diffAdded" })
hl(0, "@diff.minus", { link = "diffRemoved" })
hl(0, "@diff.delta", { link = "diffChanged" })

hl(0, "@markup.heading", { link = "Title" })
hl(0, "@markup.raw", { link = "@text.literal" })
hl(0, "@markup.link", { link = "Underlined" })
hl(0, "@markup.link.url", { link = "@text.uri" })
hl(0, "@markup.list", { fg = c5 })
hl(0, "@markup.quote", { fg = c8 })

hl(0, "@module", { fg = c9 })
hl(0, "@module.builtin", { fg = c1 })
hl(0, "@attribute", { fg = c5 })
hl(0, "@string.special.symbol", { fg = c9 })
hl(0, "@namespace", { fg = c9 })
hl(0, "@qualifier", { link = "Type" })

hl(0, "LazyNormal", { bg = bg })
hl(0, "LazyButton", { fg = c5, bg = c0 })
hl(0, "LazyButtonActive", { fg = bg, bg = c5 })
hl(0, "LazyReasonPlugin", { fg = c6 })
hl(0, "LazyReasonStart", { fg = c3 })
hl(0, "LazyReasonSource", { fg = c4 })
hl(0, "LazyReasonAnon", { fg = c8 })
hl(0, "LazyReasonRuntime", { fg = c5 })
hl(0, "LazySpecial", { fg = c11 })
hl(0, "LazyDir", { fg = c5 })

hl(0, "NoiceCmdlinePopup", { bg = c0 })
hl(0, "NoiceCmdlinePopupBorder", { fg = c5 })
hl(0, "NoiceMini", { fg = c8 })

hl(0, "FlashLabel", { fg = bg, bg = c5 })
hl(0, "FlashBackdrop", { fg = c8 })
hl(0, "FlashMatch", { fg = bg, bg = c3 })
hl(0, "FlashCurrent", { fg = bg, bg = c5 })

hl(0, "WhichKey", { fg = c5 })
hl(0, "WhichKeyGroup", { fg = c3 })
hl(0, "WhichKeyDesc", { fg = fg })
hl(0, "WhichKeySeparator", { fg = c8 })
hl(0, "WhichKeyFloat", { bg = c0 })
hl(0, "WhichKeyBorder", { fg = c5 })

hl(0, "BlinkCmpMenu", { bg = c0 })
hl(0, "BlinkCmpMenuBorder", { fg = c5 })
hl(0, "BlinkCmpDoc", { bg = c0 })
hl(0, "BlinkCmpDocBorder", { fg = c5 })
hl(0, "BlinkCmpSelection", { bg = c8 })
hl(0, "BlinkCmpSource", { fg = c8 })
hl(0, "BlinkCmpLabel", { fg = fg })
hl(0, "BlinkCmpLabelMatch", { fg = c5 })
hl(0, "BlinkCmpLabelDeprecated", { fg = c8 })
hl(0, "BlinkCmpKindKeyword", { fg = c5 })
hl(0, "BlinkCmpKindVariable", { fg = fg })
hl(0, "BlinkCmpKindConstant", { fg = c9 })
hl(0, "BlinkCmpKindReference", { fg = c9 })
hl(0, "BlinkCmpKindValue", { fg = c9 })
hl(0, "BlinkCmpKindFunction", { fg = c5 })
hl(0, "BlinkCmpKindMethod", { fg = c5 })
hl(0, "BlinkCmpKindConstructor", { fg = c9 })
hl(0, "BlinkCmpKindArray", { fg = c9 })
hl(0, "BlinkCmpKindObject", { fg = c9 })
hl(0, "BlinkCmpKindClass", { fg = c3 })
hl(0, "BlinkCmpKindStruct", { fg = c3 })
hl(0, "BlinkCmpKindModule", { fg = c9 })
hl(0, "BlinkCmpKindProperty", { fg = c6 })
hl(0, "BlinkCmpKindField", { fg = c6 })
hl(0, "BlinkCmpKindTypeParameter", { fg = c3 })
hl(0, "BlinkCmpKindEnum", { fg = c3 })
hl(0, "BlinkCmpKindSnippet", { fg = c5 })
hl(0, "BlinkCmpKindColor", { fg = c11 })
hl(0, "BlinkCmpKindFile", { fg = fg })
hl(0, "BlinkCmpKindFolder", { fg = fg })
hl(0, "BlinkCmpKindEnumMember", { fg = c3 })
hl(0, "BlinkCmpKindConstant", { fg = c9 })
hl(0, "BlinkCmpKindStruct", { fg = c3 })
hl(0, "BlinkCmpKindEvent", { fg = c5 })
hl(0, "BlinkCmpKindOperator", { fg = c3 })
hl(0, "BlinkCmpKindTypeParameter", { fg = c3 })
hl(0, "BlinkCmpKindCopilot", { fg = c4 })

hl(0, "DiagnosticError", { fg = c1 })
hl(0, "DiagnosticWarn", { fg = c3 })
hl(0, "DiagnosticInfo", { fg = c5 })
hl(0, "DiagnosticHint", { fg = c8 })
hl(0, "DiagnosticOk", { fg = c3 })
hl(0, "DiagnosticUnderlineError", { sp = c1, undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = c3, undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = c5, undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = c8, undercurl = true })
hl(0, "DiagnosticVirtualTextError", { fg = c1 })
hl(0, "DiagnosticVirtualTextWarn", { fg = c3 })
hl(0, "DiagnosticVirtualTextInfo", { fg = c5 })
hl(0, "DiagnosticVirtualTextHint", { fg = c8 })
hl(0, "DiagnosticFloatingError", { fg = c1 })
hl(0, "DiagnosticFloatingWarn", { fg = c3 })
hl(0, "DiagnosticFloatingInfo", { fg = c5 })
hl(0, "DiagnosticFloatingHint", { fg = c8 })
hl(0, "DiagnosticSignError", { fg = c1 })
hl(0, "DiagnosticSignWarn", { fg = c3 })
hl(0, "DiagnosticSignInfo", { fg = c5 })
hl(0, "DiagnosticSignHint", { fg = c8 })

hl(0, "GitSignsAdd", { fg = c3 })
hl(0, "GitSignsChange", { fg = c5 })
hl(0, "GitSignsDelete", { fg = c1 })
hl(0, "GitSignsAddLn", { bg = c2 })
hl(0, "GitSignsChangeLn", { bg = c3 })
hl(0, "GitSignsDeleteLn", { bg = c1 })
hl(0, "GitSignsAddNr", { fg = c3 })
hl(0, "GitSignsChangeNr", { fg = c5 })
hl(0, "GitSignsDeleteNr", { fg = c1 })

hl(0, "MiniIndentscopeSymbol", { fg = c8 })

hl(0, "TroubleNormal", { bg = bg })

hl(0, "SnacksIndent", { fg = c8 })
hl(0, "SnacksIndentScope", { fg = c5 })
hl(0, "SnacksBackdrop", { bg = bg })
hl(0, "SnacksPicker", { bg = bg })

vim.opt.background = "dark"
