; ---- 💫 https://github.com/JaKooLit 💫 ----
; wallust template - colors-spicetify

[Base]
text               = {{foreground}}
subtext            = {{color7}}
main               = {{background}}
sidebar            = {{color0}}
player             = {{color0}}
card               = {{color1}}
shadow             = {{color0}}
selected-row       = {{color2}}
button             = {{color5}}
button-active      = {{color2}}
button-disabled    = {{color8}}
tab-active         = {{color5}}
notification       = {{color5}}
notification-error = {{color1}}
misc               = {{color5}}
