if status is-interactive
    # Set theme
    set -g theme_nerd_fonts yes
    set -g theme_show_ssh_username no
    set -g theme_show_private_ip yes
    set -g theme_public_ip no

    # Wallpaper-based colors (generated by wallust)
    if test -f "$HOME/.config/fish/wallust-colors.fish"
        source "$HOME/.config/fish/wallust-colors.fish"
    end
end
set -x http_proxy http://172.16.10.29:8080
set -x https_proxy http://172.16.10.29:8080
set -x no_proxy "localhost,127.0.0.1,::1,192.168.88.0/24"
set -x PATH ~/.local/bin $PATH
set -x PATH ~/.local/bin $PATH
set -x PATH ~/.spicetify $PATH
set -x PATH /home/ian/.opencode/bin $PATH
alias ls='eza -al --color=always --group-directories-first --icons'
