# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1F1F1F)
$foreground = rgb(F0F0F0)
$color0 = rgb(464546)
$color1 = rgb(3E3E3E)
$color2 = rgb(616162)
$color3 = rgb(828181)
$color4 = rgb(858585)
$color5 = rgb(9D9C9D)
$color6 = rgb(9F9E9F)
$color7 = rgb(E1E1E1)
$color8 = rgb(9E9D9E)
$color9 = rgb(535253)
$color10 = rgb(828182)
$color11 = rgb(ADACAC)
$color12 = rgb(B2B1B1)
$color13 = rgb(D2D1D1)
$color14 = rgb(D4D3D4)
$color15 = rgb(E1E1E1)
