; ---- 💫 https://github.com/JaKooLit 💫 ----
; wallust template - colors-spicetify

[Base]
text               = F0F0F0
subtext            = E1E1E1
main               = 1F1F1F
sidebar            = 464546
player             = 464546
card               = 3E3E3E
shadow             = 464546
selected-row       = 616162
button             = 9D9C9D
button-active      = 616162
button-disabled    = 9E9D9E
tab-active         = 9D9C9D
notification       = 9D9C9D
notification-error = 3E3E3E
misc               = 9D9C9D
