# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers
$lock = $scriptsDir/LockScreen.sh
$SwwwRandom = $UserScripts/WallpaperAutoChange.sh
$livewallpaper=""

# wallpaper stuff
exec-once = awww-daemon --format xrgb
#exec-once = mpvpaper '*' -o "load-scripts=no no-audio --loop" $livewallpaper

# wallpaper random
#exec-once = $SwwwRandom $wallDIR # random wallpaper switcher every 30 minutes

# Startup
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Polkit (Polkit Gnome / KDE)
exec-once = $scriptsDir/Polkit.sh

# starup apps
exec-once = nm-applet --indicator
exec-once = dunst
#exec-once = ags
exec-once = blueman-applet
#exec-once = rog-control-center
exec-once = ln -sf $XDG_RUNTIME_DIR/hypr /tmp/hypr && LC_TIME=en_DK.UTF-8 waybar
exec-once = qs # quickshell AGS Desktop Overview alternative

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

#work_setup
# Create workspace 9 first, then launch app
#exec-once = hyprctl dispatch workspace 9
#exec-once = [workspace 9] remmina -c /home/ian/.remmina/group_rdp_work_192-168-79-33.remmina
# Start the daemon (no & needed - Hyprland handles backgrounding)
exec-once = /home/ian/.local/bin/awww-daemon --format xrgb

# Wait a moment, then set wallpaper
#exec-once = sleep 1 && /home/ian/.local/bin/awww img --transition-type wipe "/home/ian/Pictures/wallpapers/Northern Lights3.png"

#exec-once = kitty -e nvim /home/ian/Projects
exec-once = brave-browser-stable

# Starting hypridle to start hyprlock
exec-once = hypridle


# Here are list of features available but disabled by default
# exec-once = awww-daemon --format xrgb && awww img $HOME/Pictures/wallpapers/mecha-nostalgia.png  # persistent wallpaper

#gnome polkit for nixos
#exec-once = $scriptsDir/Polkit-NixOS.sh

# xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
#exec-once = $scriptsDir/PortalHyprland.sh
# Auto-start Hidamari with video wallpaper
#exec-once = flatpak run io.github.jeffshee.Hidamari
#exec-once = flatpak run io.github.jeffshee.Hidamari 
